### ISSUE TITLE
Unclean C Operators page

### ISSUE THREAD

**Issue by wundrweapon** [bvanseg/bvanseg.github.io#1] opened 2019-10-28 00:30 UTC
The Operators page for C is somewhat misinformative:

* The division operator does not warn the reader that division between integers rounds toward -∞ and return an integer
* The left shift, assignment left shift, and assignment right shift operators incorrectly use the `«` and `»` characters instead of `<<` and `>>`
* The example for the decrement operator reads `A-;` instead of `A--;`
* The increment and decrement operators do not explain (or at least reference) the pre/post distinction

and its formatting is inconsistent:

* The arithmetic and miscellaneous sections' "usage" areas contain example code and an explanation
* Relational, conditional/logical, and bitwise sections contain example code and the result in one syntactically-incorrect line
* Assignment sections have example code and a commented explanation (with some slightly jarring spacing)

**Comment by wundrweapon** [comment] 2019-10-28 00:33
I should clarify that I'm not against example code and the result or an explanation being together, but the reader can be confused when the non-code element(s) are rendered in a monospace font, suggesting they are code. Speaking of [fonts and formatting](https://bestmotherfucking.website/)...

**Comment by bvanseg** [comment] 2019-10-28 01:49
Points 2, 3, and 4 have been addressed since the time of writing this comment. Point 1 is to be addressed in a different tutorial. Point 5 will be introduced some time in the future.

Leaving this issue open until point 5 is addressed.

**Comment by bvanseg** [comment] 2019-10-29 16:42
Point 4 has since been addressed. The issue is now considered closed. Should you have any additional grievances or suggestions with the site, you may open up another issue with said grievances/suggestions, or alternatively open a Pull Request to fix the issues yourself.

**Closed by bvanseg** 2019-10-29 16:42 UTC
Labels: enhancement
